<?xml version="1.0" encoding="utf-8" ?>

<definitions targetNamespace="http://manufacturing.org/wsdl/purchase/bp1"
             name="POService"
             xmlns:tns="http://manufacturing.org/wsdl/purchase/bp1"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:sns="http://manufacturing.org/xsd/purchase">

    <types>
        <xsd:schema targetNamespace="http://manufacturing.org/wsdl/purchase/bp1">
            <xsd:import schemaLocation="purchaseOrder.xsd" namespace="http://manufacturing.org/xsd/purchase"/>
        </xsd:schema>
    </types>
    
    <message name="POMessage">
        <part name="purchaseOrder"
              element="sns:purchaseOrder"></part>
    </message>
    
    <message name="orderFaultType">
        <part name="faultInfo"
              type="xsd:string"></part>
    </message>
    
    <portType name="purchaseOrderPT">
        <operation name="sendPurchaseOrder">
            <input name="sendPurchaseOrderRequest" message="tns:POMessage"></input>
            <output name="sendPurchaseOrderReply" message="tns:POMessage"></output>
            <fault name="cannotCompleteOrder"
                   message="tns:orderFaultType"></fault>
        </operation>
    </portType>
    
    <binding name="purchaseOrderBinding"
             type="tns:purchaseOrderPT">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="sendPurchaseOrder">
            <soap:operation style="rpc"/>
            <input name="sendPurchaseOrderRequest">
                <soap:body parts="purchaseOrder"
                           use="literal"/>
            </input>
            <output name="sendPurchaseOrderReply">
                <soap:body parts="purchaseOrder"
                           use="literal"/>
            </output>
            <fault name="cannotCompleteOrder">
                <soap:fault name="cannotCompleteOrder"
                            use="literal"/>
            </fault>
        </operation>
    </binding>

    <service name="purchaseOrderService">
        <port name="purchaseOrderPort"
              binding="tns:purchaseOrderBinding">
            <soap:address location="http://localhost:12100/wsdl/purchase/PurchaseOrder/Servicelocation/bp1"/>
        </port>
    </service>
    
    <plink:partnerLinkType name="purchasingLT">
        <plink:role name="purchaseService"
                    portType="tns:purchaseOrderPT"></plink:role>
    </plink:partnerLinkType>
</definitions>
